import type { TradeIdeaRow, DigestRow } from '@/types/Feed'
import type { WatchlistItemWithQuote } from '@/types/Watchlist'

export const DEMO_THESIS = {
  name: 'Alex',
  goals: ['Long-term growth', 'Tech sector exposure'],
  riskTolerance: 6,
  timeHorizon: '1-3 years',
  capitalRange: '$10K - $50K',
  sectors: ['Technology', 'Energy'],
  industries: ['AI / Machine Learning', 'Semiconductors', 'Clean Energy'],
  strategies: ['Momentum', 'Earnings plays'],
  tickers: ['AAPL', 'NVDA', 'TSLA', 'MSFT', 'AMZN'],
  experience: 'Intermediate',
}

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString()
}

export const DEMO_IDEAS: TradeIdeaRow[] = [
  {
    id: 'demo-1',
    card_type: 'trade_idea',
    ticker: 'NVDA',
    direction: 'buy',
    headline: 'NVDA surges on record data center demand as AI spending accelerates',
    event_summary: 'Nvidia reported data center revenue up 154% YoY, beating estimates by $2B [1]',
    reasoning: [
      'Data center revenue hit $26.3B, driven by hyperscaler AI infrastructure buildout [1]',
      'Management raised next-quarter guidance 10% above consensus expectations [2]',
      'Stock is trading 8% below its 30-day high, offering a potential entry point [3]',
    ],
    risks: [
      'Valuation already prices in aggressive growth — limited margin for disappointment',
      'Export restrictions to China could impact future revenue',
    ],
    watch_for: 'Watch for AMD earnings next week — competitive pressure could shift sentiment',
    sources: [
      { id: 1, title: 'Nvidia Beats Estimates on Record Data Center Revenue', url: 'https://example.com/reuters/nvda-earnings', publisher: 'Reuters' },
      { id: 2, title: 'Nvidia Raises Guidance, Signals Strong AI Demand', url: 'https://example.com/bloomberg/nvda-guidance', publisher: 'Bloomberg' },
      { id: 3, title: 'NVDA Technical Analysis: Key Levels to Watch', url: 'https://example.com/marketwatch/nvda-technicals', publisher: 'MarketWatch' },
    ],
    confidence_score: 0.82,
    time_horizon: 'weeks',
    price_at_generation: 892.50,
    status: 'active',
    extra_data: null,
    created_at: hoursAgo(2),
  },
  {
    id: 'demo-2',
    card_type: 'trade_idea',
    ticker: 'TSLA',
    direction: 'hold',
    headline: 'Tesla delivery miss raises questions, but energy segment shines',
    event_summary: 'Tesla delivered 435K vehicles in Q1, below the 470K consensus estimate [1]',
    reasoning: [
      'Vehicle deliveries fell short, but energy storage deployments doubled YoY [1]',
      'Price cuts are pressuring automotive margins — gross margin dropped to 17.4% [2]',
      'Energy and services revenue now represents 15% of total, up from 8% last year [3]',
    ],
    risks: [
      'Continued price competition in China could erode margins further',
      'FSD timeline remains uncertain — regulatory approval unclear',
    ],
    watch_for: 'Robotaxi unveil event in August could be a major catalyst',
    sources: [
      { id: 1, title: 'Tesla Q1 Deliveries Miss Estimates', url: 'https://example.com/cnbc/tsla-deliveries', publisher: 'CNBC' },
      { id: 2, title: 'Tesla Margins Pressured by Price War', url: 'https://example.com/ft/tsla-margins', publisher: 'Financial Times' },
      { id: 3, title: 'Tesla Energy Business Emerges as Growth Engine', url: 'https://example.com/barrons/tsla-energy', publisher: 'Barrons' },
    ],
    confidence_score: 0.55,
    time_horizon: 'months',
    price_at_generation: 178.20,
    status: 'active',
    extra_data: null,
    created_at: hoursAgo(5),
  },
  {
    id: 'demo-3',
    card_type: 'earnings_digest',
    ticker: 'AAPL',
    direction: 'hold',
    headline: 'Apple beats on revenue but iPhone sales growth slows',
    event_summary: 'Apple posted $94.8B in revenue, beating estimates, but iPhone revenue was flat YoY [1]',
    reasoning: [
      'Services revenue hit a record $23.9B — up 14% — now the real growth engine [1]',
      'iPhone revenue was essentially flat, suggesting market saturation in key regions [2]',
      'Management highlighted AI features coming in iOS 19 as a potential upgrade driver [3]',
    ],
    risks: [
      'China revenue declined 2%, facing pressure from Huawei',
      'Regulatory risks from EU Digital Markets Act',
    ],
    watch_for: 'WWDC in June — AI feature announcements could reignite upgrade cycle',
    sources: [
      { id: 1, title: 'Apple Q2 Earnings: Services Hit Record', url: 'https://example.com/wsj/aapl-earnings', publisher: 'WSJ' },
      { id: 2, title: 'iPhone Growth Stalls in Saturated Markets', url: 'https://example.com/reuters/aapl-iphone', publisher: 'Reuters' },
      { id: 3, title: 'Apple Bets Big on AI to Drive Upgrades', url: 'https://example.com/verge/aapl-ai', publisher: 'The Verge' },
    ],
    confidence_score: 0.65,
    time_horizon: 'months',
    price_at_generation: 213.40,
    status: 'active',
    extra_data: {
      card_type: 'earnings_digest',
      quarter_label: 'Q2 2026',
      management_tone: 'Tim Cook sounded cautiously optimistic — excited about AI integration but acknowledged headwinds in China. CFO emphasized services margin expansion as a key priority.',
      analyst_view: '32 out of 40 analysts rate Apple a Buy, with an average price target of $235 — about 10% above today\'s price. Most see services as the long-term story.',
      thesis_connection: 'Aligns with your tech sector focus. Services growth supports the long-term thesis, but flat iPhone sales may limit near-term upside.',
    },
    created_at: hoursAgo(8),
  },
  {
    id: 'demo-4',
    card_type: 'trade_idea',
    ticker: 'MSFT',
    direction: 'buy',
    headline: 'Azure growth reaccelerates to 31% as enterprise AI adoption takes off',
    event_summary: 'Microsoft reported Azure revenue growth of 31%, up from 28% last quarter [1]',
    reasoning: [
      'Azure AI services contributed 7 percentage points to cloud growth — up from 3 points prior quarter [1]',
      'Copilot enterprise seats surpassed 2M, with 60% of Fortune 500 now onboarded [2]',
      'Free cash flow grew 18% YoY, funding aggressive AI infrastructure investment [3]',
    ],
    risks: [
      'AI infrastructure spending is front-loaded — returns may take quarters to materialize',
      'Google Cloud and AWS are competing aggressively on pricing',
    ],
    watch_for: 'Azure consumption metrics in next quarterly update will signal if growth is sustainable',
    sources: [
      { id: 1, title: 'Microsoft Azure Growth Beats Expectations', url: 'https://example.com/reuters/msft-azure', publisher: 'Reuters' },
      { id: 2, title: 'Copilot Adoption Surges Among Enterprise', url: 'https://example.com/bloomberg/msft-copilot', publisher: 'Bloomberg' },
      { id: 3, title: 'Microsoft Ramps AI Capex to $14B', url: 'https://example.com/wsj/msft-capex', publisher: 'WSJ' },
    ],
    confidence_score: 0.78,
    time_horizon: 'weeks',
    price_at_generation: 445.80,
    status: 'active',
    extra_data: null,
    created_at: hoursAgo(12),
  },
  {
    id: 'demo-5',
    card_type: 'trade_idea',
    ticker: 'AMZN',
    direction: 'buy',
    headline: 'AWS margin expansion signals inflection as AI workloads scale',
    event_summary: 'AWS operating margin hit 37.6%, up from 30.3% a year ago, as AI workloads grow [1]',
    reasoning: [
      'AWS operating margin expanded 730bps YoY — AI workloads carry higher margins [1]',
      'Advertising revenue grew 24%, now a $56B annual run rate [2]',
      'Management guided for accelerating revenue growth next quarter [3]',
    ],
    risks: [
      'Retail margins remain thin — most profit comes from AWS and advertising',
      'Antitrust scrutiny could limit expansion into new verticals',
    ],
    watch_for: 'Prime Day results in July will test consumer spending strength',
    sources: [
      { id: 1, title: 'AWS Margins Surge on AI Workload Growth', url: 'https://example.com/ft/amzn-aws', publisher: 'Financial Times' },
      { id: 2, title: 'Amazon Advertising Hits New Revenue Record', url: 'https://example.com/cnbc/amzn-ads', publisher: 'CNBC' },
      { id: 3, title: 'Amazon Guides Higher, Stock Rallies', url: 'https://example.com/marketwatch/amzn-guidance', publisher: 'MarketWatch' },
    ],
    confidence_score: 0.74,
    time_horizon: 'weeks',
    price_at_generation: 198.30,
    status: 'active',
    extra_data: null,
    created_at: hoursAgo(18),
  },
]

export const DEMO_EXTRA_IDEAS: TradeIdeaRow[] = [
  {
    id: 'demo-gen-1',
    card_type: 'trade_idea',
    ticker: 'NVDA',
    direction: 'buy',
    headline: 'New NVIDIA chip architecture leaked — next-gen Blackwell Ultra targets 2x inference speed',
    event_summary: 'Reports suggest NVIDIA\'s next GPU architecture doubles AI inference throughput [1]',
    reasoning: [
      'If confirmed, Blackwell Ultra could extend NVIDIA\'s moat in AI training and inference [1]',
      'Major cloud providers are already placing pre-orders according to supply chain checks [2]',
      'Stock pulled back 5% this week, creating a potential buying opportunity [3]',
    ],
    risks: [
      'Leak may be inaccurate or timeline may slip',
      'AMD MI400 launching in same window could pressure pricing',
    ],
    watch_for: 'Official announcement expected at GTC in November',
    sources: [
      { id: 1, title: 'NVIDIA Blackwell Ultra Specs Leak', url: 'https://example.com/tomshardware/nvda-leak', publisher: 'Tom\'s Hardware' },
      { id: 2, title: 'Cloud Giants Race to Secure Next-Gen NVIDIA Chips', url: 'https://example.com/reuters/nvda-orders', publisher: 'Reuters' },
      { id: 3, title: 'NVDA Pulls Back After Record Run', url: 'https://example.com/barrons/nvda-pullback', publisher: 'Barrons' },
    ],
    confidence_score: 0.71,
    time_horizon: 'months',
    price_at_generation: 885.10,
    status: 'active',
    extra_data: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-gen-2',
    card_type: 'trade_idea',
    ticker: 'MSFT',
    direction: 'buy',
    headline: 'Microsoft lands $10B Pentagon cloud contract, cementing government AI leadership',
    event_summary: 'DOD awarded Microsoft a $10B multi-cloud contract for classified AI workloads [1]',
    reasoning: [
      'This is the largest government cloud deal in history, beating out AWS and Google [1]',
      'Government cloud carries premium margins and multi-year revenue visibility [2]',
      'Contract validates Azure\'s security capabilities for the most sensitive workloads [3]',
    ],
    risks: [
      'AWS likely to protest the award, which could delay implementation',
      'Government contracts have execution risk and timeline uncertainty',
    ],
    watch_for: 'Whether AWS files a formal protest within the 30-day window',
    sources: [
      { id: 1, title: 'Microsoft Wins $10B Pentagon Cloud Contract', url: 'https://example.com/wsj/msft-pentagon', publisher: 'WSJ' },
      { id: 2, title: 'Government Cloud Market Analysis', url: 'https://example.com/gartner/gov-cloud', publisher: 'Gartner' },
      { id: 3, title: 'Azure Classified Cloud Gets Top Security Rating', url: 'https://example.com/fedscoop/azure-security', publisher: 'FedScoop' },
    ],
    confidence_score: 0.68,
    time_horizon: 'months',
    price_at_generation: 448.20,
    status: 'active',
    extra_data: null,
    created_at: new Date().toISOString(),
  },
]

export const DEMO_DIGEST: DigestRow = {
  id: 'demo-digest-1',
  greeting: 'Good morning, Alex. Big moves in AI and energy today — here\'s what matters for your thesis.',
  sections: [
    {
      label: 'AI CHIP WARS',
      body: 'Your top holding NVDA jumped 4.2% after reporting blowout data center numbers [1]. The stock is now up 18% this month, fueled by hyperscaler spending that shows no sign of slowing. Meanwhile, AMD announced a new MI350 chip targeting the inference market [2] — worth watching as competition heats up.',
    },
    {
      label: 'YOUR ENERGY WATCHLIST',
      body: 'Clean energy stocks had a mixed day. Solar names rallied on new IRA funding guidance [3], but wind stocks pulled back on supply chain concerns. Tesla\'s energy division continues to quietly build momentum — battery storage deployments doubled last quarter, and it\'s becoming a meaningful part of the bull case.',
    },
    {
      label: 'EARNINGS AHEAD',
      body: 'Apple reports after the bell Thursday — the street is focused on services growth and any AI feature previews [4]. Microsoft\'s Azure numbers last week set a high bar for cloud expectations. Your watchlist has 3 companies reporting in the next 10 days.',
    },
  ],
  watch_today: 'Fed minutes release at 2 PM ET could move rate-sensitive tech names. Apple earnings Thursday after close.',
  sources: [
    { id: 1, title: 'Nvidia Data Center Revenue Hits Record', url: 'https://example.com/reuters/nvda-datacenter', publisher: 'Reuters' },
    { id: 2, title: 'AMD Unveils MI350 Inference Chip', url: 'https://example.com/anandtech/amd-mi350', publisher: 'AnandTech' },
    { id: 3, title: 'New IRA Guidance Boosts Solar Sector', url: 'https://example.com/bloomberg/solar-ira', publisher: 'Bloomberg' },
    { id: 4, title: 'What to Watch in Apple Earnings', url: 'https://example.com/cnbc/aapl-preview', publisher: 'CNBC' },
  ],
  created_at: hoursAgo(1),
}

export const DEMO_WATCHLIST: WatchlistItemWithQuote[] = [
  {
    id: 'demo-wl-1',
    user_id: 'demo',
    ticker: 'NVDA',
    added_at: hoursAgo(720),
    notes: 'Core AI holding — watching data center revenue trajectory',
    companyName: 'NVIDIA Corporation',
    price: 892.50,
    change: 36.80,
    changePercent: 4.3,
    positions: [],
  },
  {
    id: 'demo-wl-2',
    user_id: 'demo',
    ticker: 'TSLA',
    added_at: hoursAgo(720),
    notes: 'Energy segment thesis — less about cars, more about storage',
    companyName: 'Tesla, Inc.',
    price: 178.20,
    change: -3.45,
    changePercent: -1.9,
    positions: [],
  },
  {
    id: 'demo-wl-3',
    user_id: 'demo',
    ticker: 'AAPL',
    added_at: hoursAgo(720),
    notes: 'Services growth story + AI features in iOS 19',
    companyName: 'Apple Inc.',
    price: 213.40,
    change: 1.20,
    changePercent: 0.57,
    positions: [],
  },
  {
    id: 'demo-wl-4',
    user_id: 'demo',
    ticker: 'MSFT',
    added_at: hoursAgo(720),
    notes: 'Azure + Copilot — enterprise AI leader',
    companyName: 'Microsoft Corporation',
    price: 445.80,
    change: 8.90,
    changePercent: 2.04,
    positions: [],
  },
  {
    id: 'demo-wl-5',
    user_id: 'demo',
    ticker: 'AMZN',
    added_at: hoursAgo(720),
    notes: null,
    companyName: 'Amazon.com, Inc.',
    price: 198.30,
    change: 2.15,
    changePercent: 1.1,
    positions: [],
  },
]
