import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-tickr-text">
      {/* Nav */}
      <header className="flex items-center justify-between px-6 sm:px-10 py-5 max-w-3xl mx-auto">
        <Link
          href="/"
          className="font-serif italic font-bold text-[22px] text-tickr-text hover:opacity-80 transition-opacity"
          style={{ letterSpacing: "-0.02em" }}
        >
          tickr
        </Link>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 pb-24 pt-8">
        <h1 className="text-2xl font-semibold text-tickr-text mb-2">Terms of Service</h1>
        <p className="text-[13px] text-tickr-muted mb-10">Last updated: April 9, 2026</p>

        <div className="space-y-8 text-[14px] text-tickr-secondary leading-relaxed">
          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using tickr (&quot;the Service&quot;), you agree to be bound by these Terms of
              Service. If you do not agree, do not use the Service. You must be at least 18 years old
              to create an account.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">2. Not Financial Advice</h2>
            <p>
              tickr is an AI-powered investment research tool that provides informational content only.
              Nothing on the Service constitutes financial, investment, legal, or tax advice. Trade
              ideas, market summaries, and any other content generated by tickr are for informational
              and educational purposes only. You should not make investment decisions based solely on
              tickr&apos;s output.
            </p>
            <p className="mt-3">
              Always conduct your own independent research and consult with a licensed financial
              advisor before making any investment decisions. Past performance of any investment idea
              or market analysis does not guarantee future results.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">3. No Guarantee of Accuracy</h2>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
              express or implied. We do not guarantee the accuracy, completeness, timeliness, or
              reliability of any information provided through the Service, including but not limited
              to AI-generated trade ideas, market data, news summaries, and earnings analyses.
            </p>
            <p className="mt-3">
              AI-generated content may contain errors, omissions, or outdated information. Market data
              is sourced from third-party providers and may be delayed or inaccurate. We disclaim all
              warranties including merchantability, fitness for a particular purpose, and
              non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">4. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, tickr and its operators shall not be
              liable for any financial losses, investment losses, indirect, incidental, special,
              consequential, or punitive damages arising from your use of the Service or reliance on
              any content generated by the Service.
            </p>
            <p className="mt-3">
              You expressly acknowledge that the investment information provided by tickr carries
              inherent risks, and that you assume full responsibility for any investment decisions
              you make.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">5. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and
              for all activity that occurs under your account. You agree to provide accurate and
              complete information when creating your account and to keep this information current.
            </p>
            <p className="mt-3">
              You must not share your account with others or allow others to access the Service
              through your credentials.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="mt-2 ml-4 list-disc space-y-1">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
              <li>Attempt to reverse-engineer, scrape, or systematically extract data from the Service</li>
              <li>Use automated tools to access or interact with the Service without our written permission</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
              <li>Attempt to gain unauthorized access to any part of the Service or its related systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">7. Account Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at our sole discretion, with
              or without notice, for any reason including but not limited to violation of these Terms,
              suspected fraudulent activity, or extended inactivity. You may delete your account at
              any time from the Profile page.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">8. Third-Party Services</h2>
            <p>
              The Service integrates with third-party providers including Anthropic (AI), Finnhub
              (market data), and Tavily (web search). Your use of the Service is subject to these
              providers&apos; terms and privacy policies. We are not responsible for the availability,
              accuracy, or content of third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">9. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. Continued use of the Service after changes
              constitutes acceptance of the updated Terms. We will endeavor to notify users of
              material changes via email or in-app notice.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">10. Governing Law</h2>
            <p>
              These Terms are governed by applicable law. Any disputes arising from these Terms or
              your use of the Service shall be resolved through binding arbitration or in courts of
              competent jurisdiction.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-tickr-border px-6 py-8">
        <div className="max-w-3xl mx-auto text-center">
          <div className="flex items-center justify-center gap-4 text-[12px] text-tickr-muted">
            <Link href="/" className="hover:text-tickr-secondary transition-colors">Home</Link>
            <span>·</span>
            <Link href="/terms" className="hover:text-tickr-secondary transition-colors">Terms</Link>
            <span>·</span>
            <Link href="/privacy" className="hover:text-tickr-secondary transition-colors">Privacy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
