import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-tickr-bg text-tickr-text">
      <header className="flex items-center justify-between px-6 sm:px-10 py-5 max-w-2xl mx-auto">
        <Link href="/" className="no-underline hover:opacity-80 transition-opacity">
          <span
            className="font-serif italic font-bold text-[22px] text-tickr-text"
            style={{ letterSpacing: "-0.02em" }}
          >
            tickr
          </span>
          <span className="font-serif italic text-[9px] text-tickr-muted" style={{ fontWeight: 400, marginLeft: "2px", position: "relative" as const, top: "5px" }}>
            by sky
          </span>
        </Link>
        <Link href="/login" className="text-sm text-tickr-secondary hover:text-tickr-text transition-colors">
          Back to sign in
        </Link>
      </header>

      <main className="max-w-2xl mx-auto px-6 pb-24 pt-8">
        <h1 className="font-serif text-2xl font-semibold text-tickr-text mb-1">tickr Terms of Service</h1>
        <p className="text-[13px] text-tickr-muted mb-10">Last updated: April 2026</p>

        <div className="space-y-8 text-[14px] text-tickr-secondary leading-relaxed">
          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">What tickr does</h2>
            <p>
              tickr is a personal project that uses AI to generate investment research ideas based on
              your stated preferences. It does not execute trades, manage money, or provide financial
              advice.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">Not financial advice</h2>
            <p>
              Nothing on tickr constitutes financial, investment, legal, or tax advice. All trade ideas,
              digests, and analysis are AI-generated and may be inaccurate, incomplete, or outdated. You
              are solely responsible for your own investment decisions. Always consult a qualified
              financial advisor before making investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">AI-generated content</h2>
            <p>
              Trade ideas, earnings digests, and daily briefings are generated by large language models.
              These models can produce errors, hallucinate facts, or misinterpret market conditions.
              Source citations are included but should be independently verified. Past idea performance
              does not predict future results.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">Your account</h2>
            <p>
              You must provide accurate information when creating an account. You are responsible for
              maintaining the security of your credentials. One account per person. You must be at least
              18 years old to use tickr.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">Your data</h2>
            <p>
              You retain ownership of the information you provide (your thesis, watchlist, notes). By
              using tickr, you grant us permission to process this information through our AI pipeline to
              generate personalized content for you. You can export or delete your data at any time from
              your profile page.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">Acceptable use</h2>
            <p>
              Do not use tickr to redistribute AI-generated content as your own professional financial
              advice. Do not attempt to reverse-engineer, scrape, or overload the service. Do not create
              accounts for others or use automated tools to interact with the service.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">Limitation of liability</h2>
            <p>
              tickr is provided &quot;as is&quot; with no warranties. We are not liable for any financial losses
              resulting from actions taken based on tickr&apos;s AI-generated content. We are not liable for
              service interruptions, data loss, or inaccuracies in market data provided by third-party
              sources.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">Changes</h2>
            <p>
              We may update these terms at any time. Continued use of tickr after changes constitutes
              acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-tickr-text mb-2">Contact</h2>
            <p>
              Questions about these terms can be directed to{" "}
              <a href="mailto:skyluo@tickr.app" className="text-tickr-text underline hover:opacity-70">
                skyluo@tickr.app
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-tickr-border px-6 py-8">
        <div className="max-w-2xl mx-auto text-center">
          <div className="flex items-center justify-center gap-4 text-[12px] text-tickr-muted">
            <Link href="/" className="hover:text-tickr-secondary transition-colors">Home</Link>
            <span>·</span>
            <Link href="/terms" className="hover:text-tickr-secondary transition-colors">Terms</Link>
            <span>·</span>
            <Link href="/privacy" className="hover:text-tickr-secondary transition-colors">Privacy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
